### ISSUE TITLE
Syntastic broken for go files

### ISSUE THREAD

**Issue by gravis** [spf13/spf13-vim#865]
After updating spf13-vim, I noticed syntastic wasn't working any more for my go file.
I git bisect the issue to this commit: 41944496fde846a8e89c297094531ec442762e5c

**Comment by gravis** [comment]
"not working any more" = add some junk to `return`, like `return asdf`:
- in 9af9ba73cfca2d586ae6436208581379bffc22de the error is reported ("undefined: dasf")
- in 41944496fde846a8e89c297094531ec442762e5c the error is not reported

**Comment by gravis** [comment]
That's because of https://github.com/spf13/spf13-vim/commit/41944496fde846a8e89c297094531ec442762e5c#diff-4e12c6a37ff2cbb2c93d1b33324a6051R470
I managed to restore the previous behaviour with `let g:syntastic_mode_map = { 'mode': 'active', 'active_filetypes': ['go'], 'passive_filetypes': []  }`
